# Generated by Django 3.1.3 on 2020-11-26 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fen',
            field=models.CharField(max_length=92, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_side',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='pgn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, 'Game Created. Waiting for opponent'), (2, 'Game Started'), (3, 'Game Ended')], default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
