# Generated by Django 3.1.3 on 2021-01-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
