# Generated by Django 3.1.3 on 2021-01-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210102_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
